#include "AutoTilerLib.h"
#include "AutoTilerLibTypes.h"
#include "MFCC_Generator.h"
#include "GenLUT.h"
#include "MFCC_params.h"

#define RADIX2 0
#define RADIX4 1

void MFCCConfiguration(unsigned int L1Memory)
{
  SetInlineMode(ALWAYS_INLINE);
	SetSymbolDynamics();

  SetUsedFilesNames(0, 1, "MfccBasicKernels.h");
  SetGeneratedFilesNames("MFCCKernels.c", "MFCCKernels.h");

  SetL1MemorySize(L1Memory);
}

int main(int argc, char **argv)
{
  	if (TilerParseOptions(argc, argv)) GenTilingError("Failed to initialize or incorrect output arguments directory.\n");

    // Set Auto Tiler configuration, given shared L1 memory is 51200
    MFCCConfiguration(51200);
    // Load FIR basic kernels
    LoadMFCCLibrary();
    MFCC_parallel("MFCC_Kernel", FRAME_SIZE, N_FFT, NUMCEP, MFCC_COEFF_CNT, DO_DCT, 0, N_DCT); // this will be generated by nntool
    GenerateTilingCode();
    BuildFB(OutputDir, SAMPLERATE, N_FFT, MFCC_BANK_CNT, FMIN, FMAX, MFCC_COEFF_DYN);
    BuildLUT(OutputDir, FRAME_SIZE, N_FFT, N_DCT, NUMCEP, DO_DCT, RADIX2, LIFTER_COEFF, HANNING_FN);
}
